app:
    github:
        credentials: "%github.credentials%"
        subscribed_events:
            - "deployment"
            - "deployment_status"
            - "ping"
            - "push"
            - "status"
