services:
    app.cache:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments:
            - "@cache.app"
            - "@cache.app"

    github.client:
        class: AppBundle\GitHub\Client
        arguments:
            - "@router"
            - "%github.hub.secret%"
        calls:
            - ["setCredentials", ["%app.github.credentials%"]]
            - ["setLogger", ["@logger"]]
        tags:
            - name: monolog.logger
              channel: github

    github.cached_client:
        class: AppBundle\GitHub\CachedClient
        arguments:
            - "@github.client"
            - "@app.cache"

    github.hook_manager:
        class: AppBundle\GitHub\HookManager
        arguments:
            - "@github.cached_client"
            - "%app.github.subscribed_events%"
