services:
    subscriber.project:
        class: AppBundle\Subscriber\ProjectSubscriber
        arguments:
            - "@github.hook_manager"
        tags:
            - { name: kernel.event_listener, event: project.created, method: onProjectCreated }
            - { name: kernel.event_listener, event: project.deleting, method: onProjectDeleting }

    subscriber.github:
        class: AppBundle\Subscriber\GithubSubscriber
        arguments:
            - "@lopi_pusher.pusher"
        tags:
            # configured in ConnectGithubEventsToSubscriberPass
            - { name: kernel.event_listener, event: project.created, method: onProjectEvent, priority: -100 }
            - { name: kernel.event_listener, event: stage.created, method: onStageEvent, priority: -100 }
