services:
    subscriber.project.creating:
        class: AppBundle\Subscriber\ProjectCreatedSubscriber
        arguments:
            - "@github.client"
            - "%app.github.subscribed_events%"
        tags:
            - name: kernel.event_listener
              event: project.creating
              method: onProjectCreating

    subscriber.project.deleting:
        class: AppBundle\Subscriber\ProjectDeletingSubscriber
        arguments:
            - "@github.client"
            - "%app.github.subscribed_events%"
        tags:
            - name: kernel.event_listener
              event: project.deleting
              method: onProjectDeleting
